version: '3'

services:
  helloworld:
    image: helloworld-image
    container_name: helloworld-container
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - app.message=Hello World!
    ports:
      - 8080:8080
    networks:
      - helloworld-network

networks:
  helloworld-network:
    name: helloworld-network-name