version: '3'

services:

  helloworld-1:
    image: helloworld-image
    container_name: helloworld-container-1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - server.port=8080
    volumes: 
      - /tmp/computer/volume:/tmp/volume
    networks:
      - helloworld-network

  helloworld-2:
    image: helloworld-image
    container_name: helloworld-container-2
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - server.port=8081
    volumes: 
      - /tmp/computer/volume:/tmp/volume
    networks:
      - helloworld-network


networks:
  helloworld-network: