apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-helloworld
  labels:
    app: deployment-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-helloworld
  template:
    metadata:
      labels:
        app: container-helloworld
    spec:
      containers:
      - name: container-helloworld
        image: wisniewskikr/helloworld-image
        imagePullPolicy: Never
        ports:
        - containerPort: 9090
        env:
        - name: spring.application.name
          value: "service-helloworld"
        - name: server.port
          value: "9090"
        - name: management.endpoints.jmx.exposure.include
          value: "health,info,env,beans"
        - name: management.endpoints.web.exposure.include
          value: "health,info,env,beans"
        - name: helloworld.message
          value: "Hello World"
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 15
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 15
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: service-helloworld-kubernetes
spec:
  selector:
    app: container-helloworld
  ports:
    - port: 9090
      targetPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: service-helloworld-show
spec:
  type: NodePort
  selector:
    app: container-helloworld
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 32100