 services:

  first:
    container_name: first
    image: first
    build:
      context: ./springboot-helloworld-docker-compose-wait-first
      dockerfile: Dockerfile
    environment:
      API_SECOND_URL: http://second:9090/api/v1
      WAIT_HOSTS: second:9090
      WAIT_TIMEOUT: 60
    ports:
      - 8080:8080

  second:
    container_name: second
    image: second
    build:
      context: ./springboot-helloworld-docker-compose-wait-second
      dockerfile: Dockerfile
    ports:
      - 9090:9090