apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-helloworld-storage
  labels:
    app: deployment-helloworld-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-helloworld-storage
  template:
    metadata:
      labels:
        app: container-helloworld-storage
    spec:
      containers:
      - name: container-helloworld-storage
        image: wisniewskikr/springcloud-kubernetes-multiple-service-helloworld-storage-image
        ports:
        - containerPort: 9090
        env:
        - name: spring.application.name
          value: "service-helloworld-storage"
        - name: server.port
          value: "9090"
        - name: management.endpoints.jmx.exposure.include
          value: "health,info,env,beans"
        - name: management.endpoints.web.exposure.include
          value: "health,info,env,beans"
        - name: service.helloworld.message
          value: "Hello World!"
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 60
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 60
      restartPolicy: Always


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-helloworld-display
  labels:
    app: deployment-helloworld-display
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-helloworld-display
  template:
    metadata:
      labels:
        app: container-helloworld-display
    spec:
      containers:
      - name: container-helloworld-display
        image: wisniewskikr/springcloud-kubernetes-multiple-service-helloworld-display-image
        ports:
        - containerPort: 8080
        env:
        - name: spring.application.name
          value: "service-helloworld-display"
        - name: server.port
          value: "8080"
        - name: management.endpoints.jmx.exposure.include
          value: "health,info,env,beans"
        - name: management.endpoints.web.exposure.include
          value: "health,info,env,beans"
        - name: service.helloworld.storage.name
          value: "service-helloworld-storage"
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: service-helloworld-storage
spec:
  selector:
    app: container-helloworld-storage
  ports:
    - port: 9090
      targetPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: service-helloworld-storage-display
spec:
  type: NodePort
  selector:
    app: container-helloworld-storage
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 32300

---

apiVersion: v1
kind: Service
metadata:
  name: service-helloworld-display
spec:
  selector:
    app: container-helloworld-display
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: service-helloworld-display-display
spec:
  type: NodePort
  selector:
    app: container-helloworld-display
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32100