apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-1
  labels:
    app: helloworld-deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-container-1
  template:
    metadata:
      labels:
        app: helloworld-container-1
    spec:
      containers:
      - name: helloworld-container-1
        image: wisniewskikr/helloworld-image
        ports:
        - containerPort: 8080
        env:
        - name: server.port
          value: 8080
        volumeMounts:
        - mountPath: /tmp/volume
          name: helloworld-volume      
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
      restartPolicy: Always
      volumes:
      - name: helloworld-volume
        emptyDir: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-2
  labels:
    app: helloworld-deployment-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-container-2
  template:
    metadata:
      labels:
        app: helloworld-container-2
    spec:
      containers:
      - name: helloworld-container-2
        image: wisniewskikr/helloworld-image
        ports:
        - containerPort: 8081
        env:
        - name: server.port
          value: 8081
        volumeMounts:
        - mountPath: /tmp/volume
          name: helloworld-volume      
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
      restartPolicy: Always
      volumes:
      - name: helloworld-volume
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-1
spec:
  type: NodePort
  selector:
    app: helloworld-container-1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000

---

apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-2
spec:
  type: NodePort
  selector:
    app: helloworld-container-2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32000